<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Collection;
use App\Models\Product;
use App\Support\Media;
use Illuminate\Database\Seeder;

/**
 * Starter catalogue for the Heritage Grocery template — premium Indian pantry
 * staples with dietary tags, benefits, usage and nutrition. Tagged `template =
 * heritage`, so it never appears in the other templates. Idempotent.
 */
class HeritageCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $img = fn (string $id, int $w = 900, int $h = 900) => Media::unsplash($id, $w, "&h={$h}");

        $categories = [
            ['slug' => 'rice-grains', 'name' => 'Rice & Grains', 'tagline' => 'Aged basmati, red rice, millets', 'image' => $img('1586201375761-83865001e31c'), 'content' => '<p>Our rice and grains come from single-origin cooperative farms — aged basmati from Punjab, red matta rice from Kerala and foxtail, little and barnyard millets from Karnataka. Every lot is sun-dried, cleaned by hand and milled close to dispatch so it reaches you fresh.</p><h3>How to choose</h3><p>Pick aged basmati for biryani and pulao, sona masoori for everyday meals, and millets for a fibre-rich, low-GI alternative to polished rice.</p>'],
            ['slug' => 'pulses-dals', 'name' => 'Pulses & Dals', 'tagline' => 'Unpolished, protein-rich', 'image' => $img('1515543904379-3d757afe72e4'), 'content' => '<p>Unpolished dals keep their natural bran and protein. Ours are cleaned without oil or water polish, so they cook faster and taste of the field, not the factory.</p>'],
            ['slug' => 'flour-atta', 'name' => 'Flour & Atta', 'tagline' => 'Stone-ground, fresh every week', 'image' => $img('1574323347407-f5e1ad6d020b'), 'content' => '<p>Stone-grinding keeps the wheat germ and bran in the flour. We mill in small batches every week — the date is printed on every pack.</p>'],
            ['slug' => 'spices-masalas', 'name' => 'Spices & Masalas', 'tagline' => 'Sun-dried and freshly ground', 'image' => $img('1532336414038-cf19250c5757'), 'content' => '<p>Whole spices from Kerala, Andhra and Rajasthan, ground in small batches for maximum aroma. No fillers, no colours.</p>'],
            ['slug' => 'oils-ghee', 'name' => 'Oils & Ghee', 'tagline' => 'Cold-pressed oils, bilona ghee', 'image' => $img('1474979266404-7eaacbcd87c5'), 'content' => '<p>Wood-pressed (kachi ghani) oils retain their natural aroma and nutrients. Our ghee is churned from curd the traditional bilona way.</p>'],
            ['slug' => 'dry-fruits-nuts', 'name' => 'Dry Fruits & Nuts', 'tagline' => 'Premium grade, hand-sorted', 'image' => $img('1508061253366-f7da158b6d46'), 'content' => '<p>Mamra almonds, W240 cashews, Afghan raisins and Kashmiri walnuts — graded by size and packed in nitrogen-flushed pouches for freshness.</p>'],
            ['slug' => 'sweeteners', 'name' => 'Sweeteners & Honey', 'tagline' => 'Jaggery, raw honey, khandsari', 'image' => $img('1471943311424-646960669fbc'), 'content' => '<p>Unrefined sweeteners with their minerals intact — organic jaggery, raw forest honey and khandsari sugar.</p>'],
            ['slug' => 'tea-beverages', 'name' => 'Tea & Beverages', 'tagline' => 'Estate teas and traditional blends', 'image' => $img('1571934811356-5cc061b6821f'), 'content' => '<p>Assam and Darjeeling estate teas, masala chai blends and herbal infusions.</p>'],
            ['slug' => 'health-wellness', 'name' => 'Health & Wellness', 'tagline' => 'Ayurvedic staples and superfoods', 'image' => $img('1615485500704-8e990f9900f7'), 'content' => '<p>Turmeric, moringa, ashwagandha and other traditional wellness foods, tested for purity.</p>'],
            ['slug' => 'organic-foods', 'name' => 'Organic Foods', 'tagline' => 'Certified organic, farm to pack', 'image' => $img('1464226184884-fa280b87c399'), 'content' => '<p>Everything in this section is India Organic and NPOP certified — grown without synthetic fertilisers or pesticides.</p>'],
            ['slug' => 'snacks', 'name' => 'Snacks', 'tagline' => 'Roasted, baked, honest', 'image' => $img('1601050690597-df0568f70950'), 'content' => '<p>Roasted makhana, baked chips, trail mixes and traditional namkeen — no palm oil, no MSG.</p>'],
            ['slug' => 'gift-boxes', 'name' => 'Gift Boxes', 'tagline' => 'Festive hampers', 'image' => $img('1512909006721-3d6018887383'), 'content' => '<p>Curated hampers of dry fruits, spices, ghee and teas in reusable boxes — for Diwali, weddings and housewarmings.</p>'],
        ];
        $cat = [];
        foreach ($categories as $i => $c) {
            $cat[$c['slug']] = Category::updateOrCreate(['slug' => $c['slug']], $c + ['sort_order' => $i, 'description' => $c['tagline'], 'template' => 'heritage', 'is_active' => true, 'show_in_menu' => true]);
        }

        $subs = [
            'rice-grains' => ['Basmati Rice' => 'basmati-rice', 'Everyday Rice' => 'everyday-rice', 'Millets' => 'millets', 'Poha & Flattened Grains' => 'poha-flattened-grains'],
            'pulses-dals' => ['Toor, Moong & Urad' => 'toor-moong-urad', 'Chana & Rajma' => 'chana-rajma', 'Masoor & Mixed' => 'masoor-mixed'],
            'flour-atta' => ['Wheat Atta' => 'wheat-atta', 'Millet & Multigrain Flours' => 'millet-flours', 'Besan & Maida' => 'besan-maida'],
            'spices-masalas' => ['Whole Spices' => 'whole-spices', 'Ground Spices' => 'ground-spices', 'Blended Masalas' => 'blended-masalas'],
            'oils-ghee' => ['Cold-pressed Oils' => 'cold-pressed-oils', 'Ghee' => 'ghee'],
            'dry-fruits-nuts' => ['Almonds & Cashews' => 'almonds-cashews', 'Raisins & Dates' => 'raisins-dates', 'Seeds' => 'seeds'],
            'tea-beverages' => ['Black Tea' => 'black-tea', 'Herbal & Green Tea' => 'herbal-green-tea', 'Coffee' => 'coffee-heritage'],
        ];
        foreach ($subs as $parent => $children) {
            $j = 0;
            foreach ($children as $name => $slug) {
                $cat[$slug] = Category::updateOrCreate(['slug' => $slug], ['name' => $name, 'parent_id' => $cat[$parent]->id, 'sort_order' => $j++, 'template' => 'heritage', 'is_active' => true, 'show_in_menu' => true]);
            }
        }

        $veg = ['is_veg' => true, 'country_of_origin' => 'India'];
        $organic = ['Organic', 'No preservatives'];
        $products = [
            ['slug' => 'aged-basmati-rice', 'name' => 'Aged Basmati Rice', 'category' => 'basmati-rice', 'brand' => 'Annapurna Farms', 'price' => 499, 'compare_at_price' => 599, 'sizes' => ['1 kg', '5 kg'], 'images' => [$img('1586201375761-83865001e31c'), $img('1536304993881-ff6e9eefa2a6')], 'rating' => 4.8, 'review_count' => 2140, 'is_best_seller' => true, 'is_new' => true, 'description' => 'Extra-long grain basmati aged for 24 months — fluffy, separate grains with the classic pandan aroma.', 'dietary_tags' => [...$organic, 'Gluten-free'], 'benefits' => "Low glycaemic index compared with polished rice\nNaturally aromatic — no added flavours\nGrains double in length when cooked", 'usage_instructions' => 'Rinse until the water runs clear, soak 20 minutes, then cook with 1.5 cups water per cup of rice.', 'nutrition' => [['label' => 'Energy', 'value' => '350 kcal'], ['label' => 'Carbohydrates', 'value' => '78 g'], ['label' => 'Protein', 'value' => '7 g'], ['label' => 'Fat', 'value' => '0.6 g']], 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'kerala-red-matta-rice', 'name' => 'Kerala Red Matta Rice', 'category' => 'everyday-rice', 'brand' => 'Annapurna Farms', 'price' => 165, 'sizes' => ['1 kg'], 'images' => [$img('1516684732162-798a0062be99')], 'rating' => 4.6, 'review_count' => 640, 'description' => 'Parboiled red rice from the Palakkad plains with a nutty flavour and firm bite.', 'dietary_tags' => ['Organic', 'High fibre', 'Gluten-free'], 'benefits' => "Rich in magnesium and fibre\nKeeps you full longer", 'usage_instructions' => 'Soak 30 minutes; pressure-cook with 2.5 cups water per cup for 4 whistles.', 'nutrition' => [['label' => 'Energy', 'value' => '345 kcal'], ['label' => 'Fibre', 'value' => '3.2 g'], ['label' => 'Protein', 'value' => '7.5 g']], 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'sona-masoori-rice', 'name' => 'Sona Masoori Rice', 'category' => 'everyday-rice', 'brand' => 'Annapurna Farms', 'price' => 289, 'compare_at_price' => 320, 'sizes' => ['5 kg'], 'images' => [$img('1536304993881-ff6e9eefa2a6')], 'rating' => 4.5, 'review_count' => 1320, 'is_best_seller' => true, 'description' => 'Light, medium-grain rice for everyday meals — ideal for pulihora, curd rice and idli batter.', 'dietary_tags' => ['Gluten-free'], 'usage_instructions' => 'Cook with 2 cups water per cup of rice.', 'nutrition' => [['label' => 'Energy', 'value' => '360 kcal'], ['label' => 'Carbohydrates', 'value' => '80 g']], 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'foxtail-millet', 'name' => 'Foxtail Millet (Kangni)', 'category' => 'millets', 'brand' => 'Annapurna Farms', 'price' => 145, 'sizes' => ['500 g'], 'images' => [$img('1574323347407-f5e1ad6d020b')], 'rating' => 4.4, 'review_count' => 310, 'is_new' => true, 'description' => 'Ancient millet from Karnataka dryland farms — a low-GI, high-fibre substitute for rice.', 'dietary_tags' => ['Organic', 'Gluten-free', 'High fibre'], 'benefits' => "Low glycaemic index\nRich in iron and B vitamins", 'usage_instructions' => 'Soak 15 minutes, cook like rice with 2 cups water per cup. Makes excellent upma and khichdi.', 'nutrition' => [['label' => 'Energy', 'value' => '331 kcal'], ['label' => 'Protein', 'value' => '12 g'], ['label' => 'Fibre', 'value' => '8 g']], 'shelf_life' => '9 months'] + $veg,
            ['slug' => 'thick-poha', 'name' => 'Thick Poha (Flattened Rice)', 'category' => 'poha-flattened-grains', 'brand' => 'Annapurna Farms', 'price' => 68, 'sizes' => ['500 g'], 'images' => [$img('1589301760014-d929f3979dbc')], 'rating' => 4.5, 'review_count' => 540, 'description' => 'Thick-cut poha that stays fluffy — for kanda poha, chivda and quick breakfasts.', 'dietary_tags' => ['Gluten-free'], 'usage_instructions' => 'Rinse briefly, rest 5 minutes, then temper with mustard, curry leaves and peanuts.', 'shelf_life' => '6 months'] + $veg,

            ['slug' => 'unpolished-toor-dal', 'name' => 'Unpolished Toor Dal', 'category' => 'toor-moong-urad', 'brand' => 'Annapurna Farms', 'price' => 189, 'compare_at_price' => 215, 'sizes' => ['1 kg'], 'images' => [$img('1515543904379-3d757afe72e4')], 'rating' => 4.7, 'review_count' => 1860, 'is_best_seller' => true, 'description' => 'Sun-dried, unpolished arhar dal from Maharashtra — cooks in 3 whistles and tastes of the field.', 'dietary_tags' => [...$organic, 'High protein'], 'benefits' => "22 g protein per 100 g\nNo oil or water polish", 'usage_instructions' => 'Rinse, soak 20 minutes, pressure-cook with turmeric for 3–4 whistles.', 'nutrition' => [['label' => 'Energy', 'value' => '335 kcal'], ['label' => 'Protein', 'value' => '22 g'], ['label' => 'Fibre', 'value' => '15 g']], 'shelf_life' => '9 months'] + $veg,
            ['slug' => 'moong-dal-yellow', 'name' => 'Yellow Moong Dal', 'category' => 'toor-moong-urad', 'brand' => 'Annapurna Farms', 'price' => 159, 'sizes' => ['1 kg'], 'images' => [$img('1610725663727-08695a1ac3ff')], 'rating' => 4.6, 'review_count' => 920, 'description' => 'Split, husked moong — light, quick-cooking and easy to digest.', 'dietary_tags' => ['Organic', 'High protein'], 'usage_instructions' => 'No soaking needed; simmer 15 minutes for dal or khichdi.', 'nutrition' => [['label' => 'Protein', 'value' => '24 g'], ['label' => 'Fibre', 'value' => '8 g']], 'shelf_life' => '9 months'] + $veg,
            ['slug' => 'kabuli-chana', 'name' => 'Kabuli Chana (Chickpeas)', 'category' => 'chana-rajma', 'brand' => 'Annapurna Farms', 'price' => 149, 'compare_at_price' => 170, 'sizes' => ['1 kg'], 'images' => [$img('1515543904379-3d757afe72e4')], 'rating' => 4.5, 'review_count' => 700, 'description' => 'Large, creamy chickpeas for chole, hummus and salads.', 'dietary_tags' => ['High protein', 'High fibre'], 'usage_instructions' => 'Soak overnight; pressure-cook 6–7 whistles.', 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'kashmiri-rajma', 'name' => 'Kashmiri Rajma', 'category' => 'chana-rajma', 'brand' => 'Annapurna Farms', 'price' => 219, 'sizes' => ['500 g'], 'images' => [$img('1508747703725-719777637510')], 'rating' => 4.7, 'review_count' => 480, 'is_new' => true, 'description' => 'Small, dark red kidney beans from the Bhaderwah valley — creamy inside, quick to cook.', 'dietary_tags' => ['Organic', 'High protein'], 'usage_instructions' => 'Soak 8 hours; pressure-cook 5 whistles with a pinch of salt.', 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'masoor-dal-whole', 'name' => 'Whole Masoor Dal', 'category' => 'masoor-mixed', 'brand' => 'Annapurna Farms', 'price' => 129, 'sizes' => ['1 kg'], 'images' => [$img('1610725663727-08695a1ac3ff')], 'rating' => 4.4, 'review_count' => 260, 'description' => 'Brown whole lentils with an earthy flavour — for sabut masoor and hearty soups.', 'dietary_tags' => ['High protein', 'High fibre'], 'shelf_life' => '9 months'] + $veg,

            ['slug' => 'stone-ground-wheat-atta', 'name' => 'Stone-ground Whole Wheat Atta', 'category' => 'wheat-atta', 'brand' => 'Annapurna Farms', 'price' => 329, 'compare_at_price' => 360, 'sizes' => ['5 kg'], 'images' => [$img('1574323347407-f5e1ad6d020b')], 'rating' => 4.8, 'review_count' => 2410, 'is_best_seller' => true, 'description' => 'Sharbati wheat from Sehore, chakki-ground the week it ships — soft rotis that stay soft.', 'dietary_tags' => [...$organic, 'Stone-ground', 'High fibre'], 'benefits' => "Bran and germ retained\nMilled weekly in small batches", 'usage_instructions' => 'Knead with lukewarm water, rest 20 minutes, roll thin.', 'nutrition' => [['label' => 'Energy', 'value' => '340 kcal'], ['label' => 'Protein', 'value' => '12 g'], ['label' => 'Fibre', 'value' => '11 g']], 'shelf_life' => '3 months'] + $veg,
            ['slug' => 'ragi-flour', 'name' => 'Ragi (Finger Millet) Flour', 'category' => 'millet-flours', 'brand' => 'Annapurna Farms', 'price' => 95, 'sizes' => ['1 kg'], 'images' => [$img('1574323347407-f5e1ad6d020b')], 'rating' => 4.5, 'review_count' => 380, 'description' => 'Calcium-rich ragi from Karnataka, stone-ground for rotis, mudde and porridge.', 'dietary_tags' => ['Organic', 'Gluten-free', 'Stone-ground'], 'benefits' => "Highest calcium of any grain\nNaturally gluten-free", 'nutrition' => [['label' => 'Calcium', 'value' => '344 mg'], ['label' => 'Protein', 'value' => '7 g']], 'shelf_life' => '4 months'] + $veg,
            ['slug' => 'besan-gram-flour', 'name' => 'Besan (Gram Flour)', 'category' => 'besan-maida', 'brand' => 'Annapurna Farms', 'price' => 110, 'sizes' => ['1 kg'], 'images' => [$img('1515543904379-3d757afe72e4')], 'rating' => 4.4, 'review_count' => 290, 'description' => 'Fine chana dal flour for pakoras, kadhi and ladoos.', 'dietary_tags' => ['Gluten-free', 'High protein'], 'shelf_life' => '6 months'] + $veg,

            ['slug' => 'stone-ground-garam-masala', 'name' => 'Stone-ground Garam Masala', 'category' => 'blended-masalas', 'brand' => 'Masala Ghar', 'price' => 145, 'compare_at_price' => 165, 'sizes' => ['100 g'], 'images' => [$img('1506368249639-73a05d6f6488'), $img('1532336414038-cf19250c5757')], 'rating' => 4.9, 'review_count' => 1540, 'is_best_seller' => true, 'description' => 'Twelve whole spices, roasted and stone-ground in small batches — cardamom-forward and deeply aromatic.', 'dietary_tags' => ['No preservatives', 'Stone-ground'], 'ingredients' => 'Coriander, cumin, black pepper, green cardamom, cinnamon, cloves, black cardamom, nutmeg, mace, bay leaf, star anise, fennel', 'usage_instructions' => 'Add at the end of cooking to keep the aroma.', 'shelf_life' => '9 months'] + $veg,
            ['slug' => 'lakadong-turmeric', 'name' => 'Lakadong Turmeric Powder', 'category' => 'ground-spices', 'brand' => 'Masala Ghar', 'price' => 199, 'sizes' => ['200 g'], 'images' => [$img('1615485500704-8e990f9900f7')], 'rating' => 4.8, 'review_count' => 1120, 'is_new' => true, 'description' => 'High-curcumin (7%+) turmeric from Meghalaya’s Jaintia hills.', 'dietary_tags' => $organic, 'benefits' => "7–9% curcumin — among the highest in the world\nSingle-origin, sun-dried", 'usage_instructions' => 'Half a teaspoon in warm milk, or as you would use any haldi.', 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'kashmiri-red-chilli', 'name' => 'Kashmiri Red Chilli Powder', 'category' => 'ground-spices', 'brand' => 'Masala Ghar', 'price' => 129, 'sizes' => ['200 g'], 'images' => [$img('1509358271058-acd22cc93898')], 'rating' => 4.6, 'review_count' => 640, 'description' => 'Deep colour, gentle heat — the chilli for rogan josh, tandoori marinades and dal tadka.', 'dietary_tags' => ['No preservatives'], 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'whole-cumin-seeds', 'name' => 'Whole Cumin Seeds', 'category' => 'whole-spices', 'brand' => 'Masala Ghar', 'price' => 85, 'sizes' => ['200 g'], 'images' => [$img('1596040033229-a9821ebd058d')], 'rating' => 4.5, 'review_count' => 420, 'description' => 'Bold Gujarat cumin — toast whole for tadka or grind fresh.', 'dietary_tags' => ['Organic'], 'shelf_life' => '18 months'] + $veg,
            ['slug' => 'green-cardamom', 'name' => 'Green Cardamom (8 mm bold)', 'category' => 'whole-spices', 'brand' => 'Masala Ghar', 'price' => 349, 'compare_at_price' => 399, 'sizes' => ['100 g'], 'images' => [$img('1532336414038-cf19250c5757')], 'rating' => 4.8, 'review_count' => 380, 'description' => 'Bold green pods from Idukki with intact seeds and a sweet, floral aroma.', 'dietary_tags' => ['Organic'], 'shelf_life' => '12 months'] + $veg,

            ['slug' => 'a2-gir-cow-ghee', 'name' => 'A2 Gir Cow Bilona Ghee', 'category' => 'ghee', 'brand' => 'Gaushala Naturals', 'price' => 1299, 'compare_at_price' => 1499, 'sizes' => ['500 ml', '1 L'], 'images' => [$img('1589985270826-4b7bb135bc9d')], 'rating' => 4.9, 'review_count' => 2080, 'is_best_seller' => true, 'description' => 'Hand-churned from curd (bilona method) using A2 milk from free-grazing Gir cows. Granular, golden, nutty.', 'dietary_tags' => ['No preservatives'], 'benefits' => "Traditional bilona method — 30 litres of milk per kilo\nRich in butyric acid and fat-soluble vitamins", 'usage_instructions' => 'A teaspoon on hot rotis, dal or rice; ideal for tadka and sweets.', 'nutrition' => [['label' => 'Energy', 'value' => '900 kcal'], ['label' => 'Fat', 'value' => '99.8 g']], 'shelf_life' => '9 months', 'storage_instructions' => 'Store at room temperature away from sunlight; use a dry spoon.'] + $veg,
            ['slug' => 'cold-pressed-groundnut-oil', 'name' => 'Cold-pressed Groundnut Oil', 'category' => 'cold-pressed-oils', 'brand' => 'Gaushala Naturals', 'price' => 349, 'sizes' => ['1 L'], 'images' => [$img('1474979266404-7eaacbcd87c5')], 'rating' => 4.7, 'review_count' => 860, 'description' => 'Wood-pressed (kachi ghani) peanut oil with a nutty aroma — for everyday Indian cooking and frying.', 'dietary_tags' => ['Cold-pressed', 'No preservatives'], 'benefits' => "Unrefined — natural vitamin E retained\nHigh smoke point for frying", 'shelf_life' => '6 months'] + $veg,
            ['slug' => 'cold-pressed-coconut-oil', 'name' => 'Cold-pressed Coconut Oil', 'category' => 'cold-pressed-oils', 'brand' => 'Gaushala Naturals', 'price' => 299, 'compare_at_price' => 340, 'sizes' => ['500 ml'], 'images' => [$img('1474979266404-7eaacbcd87c5')], 'rating' => 4.6, 'review_count' => 540, 'description' => 'Virgin coconut oil from Kerala copra — for cooking, hair and skin.', 'dietary_tags' => ['Organic', 'Cold-pressed'], 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'mustard-oil-kachi-ghani', 'name' => 'Kachi Ghani Mustard Oil', 'category' => 'cold-pressed-oils', 'brand' => 'Gaushala Naturals', 'price' => 279, 'sizes' => ['1 L'], 'images' => [$img('1474979266404-7eaacbcd87c5')], 'rating' => 4.5, 'review_count' => 390, 'description' => 'Pungent, cold-pressed mustard oil for pickles, Bengali and Punjabi cooking.', 'dietary_tags' => ['Cold-pressed'], 'shelf_life' => '9 months'] + $veg,

            ['slug' => 'mamra-almonds', 'name' => 'Mamra Almonds', 'category' => 'almonds-cashews', 'brand' => 'Dry Fruit Bazaar', 'price' => 899, 'compare_at_price' => 1099, 'sizes' => ['250 g', '500 g'], 'images' => [$img('1508061253366-f7da158b6d46'), $img('1608797178974-15b35a64ede9')], 'rating' => 4.8, 'review_count' => 760, 'is_best_seller' => true, 'description' => 'Small, oil-rich Mamra almonds from Iran-origin orchards — crunchier and richer than California varieties.', 'dietary_tags' => ['Vegan', 'High protein'], 'benefits' => "Higher natural oil content\nHand-sorted, nitrogen-flushed pack", 'nutrition' => [['label' => 'Energy', 'value' => '600 kcal'], ['label' => 'Protein', 'value' => '21 g'], ['label' => 'Fat', 'value' => '52 g']], 'shelf_life' => '9 months'] + $veg,
            ['slug' => 'w240-cashews', 'name' => 'W240 Whole Cashews', 'category' => 'almonds-cashews', 'brand' => 'Dry Fruit Bazaar', 'price' => 549, 'sizes' => ['500 g'], 'images' => [$img('1608797178974-15b35a64ede9')], 'rating' => 4.7, 'review_count' => 640, 'description' => 'Large, creamy W240 grade cashews from Goa.', 'dietary_tags' => ['Vegan'], 'shelf_life' => '9 months'] + $veg,
            ['slug' => 'afghan-raisins', 'name' => 'Afghan Green Raisins', 'category' => 'raisins-dates', 'brand' => 'Dry Fruit Bazaar', 'price' => 249, 'sizes' => ['250 g'], 'images' => [$img('1610614819513-58e34989848b')], 'rating' => 4.5, 'review_count' => 310, 'description' => 'Long, sweet-tart green raisins — no sugar coating.', 'dietary_tags' => ['Vegan', 'No preservatives'], 'shelf_life' => '9 months'] + $veg,
            ['slug' => 'medjool-dates', 'name' => 'Medjool Dates', 'category' => 'raisins-dates', 'brand' => 'Dry Fruit Bazaar', 'price' => 599, 'compare_at_price' => 699, 'sizes' => ['500 g'], 'images' => [$img('1590080875515-8a3a8dc5735e')], 'rating' => 4.7, 'review_count' => 420, 'is_new' => true, 'description' => 'Soft, caramel-like dates — a natural sweetener for desserts and smoothies.', 'dietary_tags' => ['Vegan', 'No preservatives'], 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'roasted-mixed-seeds', 'name' => 'Roasted Mixed Seeds', 'category' => 'seeds', 'brand' => 'Dry Fruit Bazaar', 'price' => 199, 'sizes' => ['250 g'], 'images' => [$img('1615485500704-8e990f9900f7')], 'rating' => 4.4, 'review_count' => 220, 'description' => 'Pumpkin, sunflower, flax, chia and watermelon seeds, lightly roasted.', 'dietary_tags' => ['Vegan', 'High protein', 'High fibre'], 'shelf_life' => '6 months'] + $veg,

            ['slug' => 'organic-jaggery-powder', 'name' => 'Organic Jaggery Powder', 'category' => 'sweeteners', 'brand' => 'Annapurna Farms', 'price' => 129, 'sizes' => ['500 g'], 'images' => [$img('1471943311424-646960669fbc')], 'rating' => 4.6, 'review_count' => 540, 'description' => 'Sun-dried sugarcane jaggery, unrefined and mineral-rich — for chai, sweets and everyday cooking.', 'dietary_tags' => [...$organic, 'Vegan'], 'benefits' => "Iron, magnesium and potassium retained\nNo sulphur, no bleaching", 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'raw-forest-honey', 'name' => 'Raw Forest Honey', 'category' => 'sweeteners', 'brand' => 'Wild Hive', 'price' => 449, 'compare_at_price' => 499, 'sizes' => ['500 g'], 'images' => [$img('1555211652-5c6222f971bc'), $img('1471943311424-646960669fbc')], 'rating' => 4.8, 'review_count' => 980, 'is_best_seller' => true, 'description' => 'Multi-floral honey harvested by tribal collectives in the Nilgiris — unheated, unfiltered, NMR-tested.', 'dietary_tags' => ['No preservatives'], 'benefits' => "Raw and unheated — enzymes intact\nNMR-tested for purity", 'shelf_life' => '24 months', 'storage_instructions' => 'Crystallisation is natural; warm the jar gently to liquefy.'] + $veg,

            ['slug' => 'assam-ctc-tea', 'name' => 'Assam Estate CTC Tea', 'category' => 'black-tea', 'brand' => 'Chai Bagaan', 'price' => 299, 'sizes' => ['500 g'], 'images' => [$img('1544787219-7f47ccb76574')], 'rating' => 4.7, 'review_count' => 1240, 'is_best_seller' => true, 'description' => 'Strong, malty CTC from a single Upper Assam estate — built for milk chai.', 'dietary_tags' => ['No preservatives'], 'usage_instructions' => 'One teaspoon per cup; boil with milk, sugar and ginger for 3 minutes.', 'shelf_life' => '18 months'] + $veg,
            ['slug' => 'masala-chai-blend', 'name' => 'Masala Chai Blend', 'category' => 'black-tea', 'brand' => 'Chai Bagaan', 'price' => 249, 'compare_at_price' => 279, 'sizes' => ['250 g'], 'images' => [$img('1571934811356-5cc061b6821f')], 'rating' => 4.8, 'review_count' => 860, 'is_new' => true, 'description' => 'Assam tea with cardamom, ginger, cinnamon, cloves and black pepper — no flavourings.', 'dietary_tags' => ['No preservatives'], 'ingredients' => 'Black tea, ginger, cardamom, cinnamon, cloves, black pepper', 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'tulsi-green-tea', 'name' => 'Tulsi Green Tea', 'category' => 'herbal-green-tea', 'brand' => 'Chai Bagaan', 'price' => 229, 'sizes' => ['25 bags'], 'images' => [$img('1597318181409-cf64d0b5d8a2')], 'rating' => 4.5, 'review_count' => 430, 'description' => 'Darjeeling green tea with Rama and Krishna tulsi leaves.', 'dietary_tags' => ['Organic'], 'shelf_life' => '18 months'] + $veg,
            ['slug' => 'south-indian-filter-coffee', 'name' => 'South Indian Filter Coffee', 'category' => 'coffee-heritage', 'brand' => 'Chai Bagaan', 'price' => 279, 'sizes' => ['250 g'], 'images' => [$img('1497515114629-f71d768fd07c')], 'rating' => 4.7, 'review_count' => 510, 'description' => 'Coorg Arabica and Robusta with 20% chicory, ground for the traditional filter.', 'dietary_tags' => ['No preservatives'], 'shelf_life' => '9 months'] + $veg,

            ['slug' => 'moringa-leaf-powder', 'name' => 'Moringa Leaf Powder', 'category' => 'health-wellness', 'brand' => 'Wild Hive', 'price' => 249, 'sizes' => ['200 g'], 'images' => [$img('1576045057995-568f588f82fb')], 'rating' => 4.4, 'review_count' => 260, 'description' => 'Shade-dried moringa leaves from Tamil Nadu — a spoon in smoothies, dal or chutney.', 'dietary_tags' => [...$organic, 'Vegan'], 'benefits' => "Rich in iron, calcium and vitamin A\nShade-dried to keep nutrients", 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'ashwagandha-powder', 'name' => 'Ashwagandha Root Powder', 'category' => 'health-wellness', 'brand' => 'Wild Hive', 'price' => 299, 'compare_at_price' => 349, 'sizes' => ['100 g'], 'images' => [$img('1615485500704-8e990f9900f7')], 'rating' => 4.5, 'review_count' => 340, 'description' => 'Sun-dried Nagori ashwagandha root, finely ground.', 'dietary_tags' => ['Organic'], 'usage_instructions' => 'Half a teaspoon in warm milk before bed.', 'shelf_life' => '18 months'] + $veg,
            ['slug' => 'chia-seeds', 'name' => 'Chia Seeds', 'category' => 'health-wellness', 'brand' => 'Wild Hive', 'price' => 199, 'sizes' => ['250 g'], 'images' => [$img('1615485500704-8e990f9900f7')], 'rating' => 4.5, 'review_count' => 380, 'description' => 'Black chia seeds rich in omega-3 and fibre.', 'dietary_tags' => ['Vegan', 'High fibre', 'Gluten-free'], 'shelf_life' => '12 months'] + $veg,

            ['slug' => 'organic-quinoa', 'name' => 'Organic Quinoa', 'category' => 'organic-foods', 'brand' => 'Annapurna Farms', 'price' => 349, 'sizes' => ['500 g'], 'images' => [$img('1547592180-85f173990554')], 'rating' => 4.4, 'review_count' => 210, 'description' => 'Indian-grown white quinoa from Rajasthan — light, fluffy and complete in protein.', 'dietary_tags' => [...$organic, 'Vegan', 'Gluten-free', 'High protein'], 'shelf_life' => '12 months'] + $veg,
            ['slug' => 'organic-brown-rice', 'name' => 'Organic Brown Rice', 'category' => 'organic-foods', 'brand' => 'Annapurna Farms', 'price' => 199, 'sizes' => ['1 kg'], 'images' => [$img('1536304993881-ff6e9eefa2a6')], 'rating' => 4.3, 'review_count' => 180, 'description' => 'Unpolished sona masoori with the bran intact.', 'dietary_tags' => [...$organic, 'High fibre', 'Gluten-free'], 'shelf_life' => '6 months'] + $veg,

            ['slug' => 'roasted-makhana', 'name' => 'Roasted Makhana — Himalayan Pink Salt', 'category' => 'snacks', 'brand' => 'Masala Ghar', 'price' => 179, 'compare_at_price' => 199, 'sizes' => ['100 g'], 'images' => [$img('1601050690597-df0568f70950')], 'rating' => 4.6, 'review_count' => 720, 'is_new' => true, 'description' => 'Fox nuts roasted in ghee with pink salt and black pepper.', 'dietary_tags' => ['Gluten-free', 'No preservatives'], 'nutrition' => [['label' => 'Energy', 'value' => '350 kcal'], ['label' => 'Protein', 'value' => '9 g']], 'shelf_life' => '6 months'] + $veg,
            ['slug' => 'baked-ragi-chips', 'name' => 'Baked Ragi Chips', 'category' => 'snacks', 'brand' => 'Masala Ghar', 'price' => 99, 'sizes' => ['150 g'], 'images' => [$img('1601050690597-df0568f70950')], 'rating' => 4.3, 'review_count' => 260, 'description' => 'Crunchy baked chips made from finger millet — no palm oil, no MSG.', 'dietary_tags' => ['Gluten-free', 'Vegan'], 'shelf_life' => '6 months'] + $veg,

            ['slug' => 'festive-dry-fruit-hamper', 'name' => 'Festive Dry Fruit Hamper', 'category' => 'gift-boxes', 'brand' => 'Annapurna Farms', 'price' => 1899, 'compare_at_price' => 2299, 'sizes' => ['1 box (1.2 kg)'], 'images' => [$img('1512909006721-3d6018887383'), $img('1508061253366-f7da158b6d46')], 'rating' => 4.9, 'review_count' => 310, 'is_best_seller' => true, 'is_new' => true, 'description' => 'Mamra almonds, W240 cashews, Afghan raisins, Medjool dates and pistachios in a reusable brass-finish tin.', 'dietary_tags' => ['Vegan', 'No preservatives'], 'shelf_life' => '6 months', 'max_qty' => 5] + $veg,
            ['slug' => 'pantry-starter-box', 'name' => 'Pantry Starter Box', 'category' => 'gift-boxes', 'brand' => 'Annapurna Farms', 'price' => 1499, 'sizes' => ['1 box'], 'images' => [$img('1512909006721-3d6018887383')], 'rating' => 4.7, 'review_count' => 150, 'description' => 'Aged basmati, toor dal, atta, turmeric, garam masala and A2 ghee — a complete Indian pantry for a new home.', 'dietary_tags' => ['No preservatives'], 'shelf_life' => '6 months'] + $veg,
        ];

        $models = [];
        foreach ($products as $i => $data) {
            $categorySlug = $data['category'];
            unset($data['category']);
            $models[$data['slug']] = Product::updateOrCreate(['slug' => $data['slug']], $data + [
                'category_id' => $cat[$categorySlug]->id,
                'sort_order' => $i,
                'sku' => 'HG-'.str_pad((string) ($i + 3001), 4, '0', STR_PAD_LEFT),
                'colors' => [],
                'stock' => 80,
                'is_active' => true,
                'template' => 'heritage',
            ]);
        }

        $c = fn (string $id) => Media::unsplash($id, 1200, '&h=900');
        $collections = [
            ['slug' => 'everyday-essentials', 'name' => 'Everyday Essentials', 'description' => 'Rice, dal, atta, oil and spices — the pantry you restock every month.', 'image' => $c('1586201375761-83865001e31c'), 'products' => ['sona-masoori-rice', 'unpolished-toor-dal', 'stone-ground-wheat-atta', 'cold-pressed-groundnut-oil', 'lakadong-turmeric', 'whole-cumin-seeds', 'organic-jaggery-powder', 'assam-ctc-tea']],
            ['slug' => 'healthy-breakfast', 'name' => 'Healthy Breakfast', 'description' => 'Poha, millets, honey, seeds and teas for a lighter start.', 'image' => $c('1547592180-85f173990554'), 'products' => ['thick-poha', 'foxtail-millet', 'raw-forest-honey', 'roasted-mixed-seeds', 'chia-seeds', 'tulsi-green-tea', 'organic-quinoa']],
            ['slug' => 'festive-cooking', 'name' => 'Festive Cooking', 'description' => 'Ghee, cardamom, dry fruits and basmati for the celebrations.', 'image' => $c('1585937421612-70a008356fbe'), 'is_featured' => true, 'products' => ['a2-gir-cow-ghee', 'green-cardamom', 'aged-basmati-rice', 'mamra-almonds', 'w240-cashews', 'afghan-raisins', 'festive-dry-fruit-hamper']],
            ['slug' => 'kitchen-essentials', 'name' => 'Kitchen Essentials', 'description' => 'The spice box, the oils and the flours every Indian kitchen runs on.', 'image' => $c('1532336414038-cf19250c5757'), 'products' => ['stone-ground-garam-masala', 'kashmiri-red-chilli', 'whole-cumin-seeds', 'mustard-oil-kachi-ghani', 'besan-gram-flour', 'ragi-flour']],
            ['slug' => 'premium-staples', 'name' => 'Premium Staples', 'description' => 'Single-origin, small-batch versions of the classics.', 'image' => $c('1500382017468-9049fed747ef'), 'products' => ['aged-basmati-rice', 'a2-gir-cow-ghee', 'kashmiri-rajma', 'lakadong-turmeric', 'raw-forest-honey', 'medjool-dates']],
            ['slug' => 'wellness-foods', 'name' => 'Wellness Foods', 'description' => 'Ayurvedic staples and superfoods, tested for purity.', 'image' => $c('1615485500704-8e990f9900f7'), 'products' => ['moringa-leaf-powder', 'ashwagandha-powder', 'lakadong-turmeric', 'chia-seeds', 'tulsi-green-tea', 'raw-forest-honey']],
        ];
        foreach ($collections as $i => $data) {
            $slugs = $data['products'];
            unset($data['products']);
            $collection = Collection::updateOrCreate(['slug' => $data['slug']], $data + ['sort_order' => 200 + $i, 'is_active' => true, 'template' => 'heritage']);
            $sync = [];
            foreach ($slugs as $k => $slug) {
                $sync[$models[$slug]->id] = ['sort_order' => $k];
            }
            $collection->products()->sync($sync);
        }
    }
}
